import { sources } from './sources';

export const topHeadlinesStrings = [
  {
    name: 'Country',
    options: [
      { name: 'United Arab Emirates', id: 'ae' },
      { name: 'Argentina', id: 'ar' },
      { name: 'Austria', id: 'at' },
      { name: 'Australia', id: 'au' },
      { name: 'Belgium', id: 'be' },
      { name: 'Bulgaria', id: 'bg' },
      { name: 'Brazil', id: 'br' },
      { name: 'Canada', id: 'ca' },
      { name: 'Chile', id: 'ch' },
      { name: 'China', id: 'cn' },
      { name: 'Colombia', id: 'co' },
      { name: 'Cuba', id: 'cu' },
      { name: 'Czechia', id: 'cz' },
      { name: 'Germany', id: 'de' },
      { name: 'Egypt', id: 'eg' },
      { name: 'France', id: 'fr' },
      { name: 'Great Britain', id: 'gb' },
      { name: 'Greece', id: 'gr' },
      { name: 'Hong Kong', id: 'hk' },
      { name: 'Hungary', id: 'hu' },
      { name: 'Indonesia', id: 'id' },
      { name: 'Ireland', id: 'ie' },
      { name: 'Israel', id: 'il' },
      { name: 'India', id: 'in' },
      { name: 'Italy', id: 'it' },
      { name: 'Japan', id: 'jp' },
      { name: 'Korea (the Republic of)', id: 'kr' },
      { name: 'Lithuania', id: 'lt' },
      { name: 'Latvia', id: 'lv' },
      { name: 'Morocco', id: 'ma' },
      { name: 'Mexico', id: 'mx' },
      { name: 'Malaysia', id: 'my' },
      { name: 'Nigeria', id: 'ng' },
      { name: 'Netherlands', id: 'nl' },
      { name: 'Norway', id: 'no' },
      { name: 'New Zealand', id: 'nz' },
      { name: 'Philippines', id: 'ph' },
      { name: 'Poland', id: 'pl' },
      { name: 'Portugal', id: 'pt' },
      { name: 'Romania', id: 'ro' },
      { name: 'Serbia', id: 'rs' },
      { name: 'Russia', id: 'ru' },
      { name: 'Saudi Arabia', id: 'sa' },
      { name: 'Sweden', id: 'se' },
      { name: 'Singapore', id: 'sg' },
      { name: 'Slovenia', id: 'si' },
      { name: 'Slovakia', id: 'sk' },
      { name: 'Thailand', id: 'th' },
      { name: 'Turkey', id: 'tr' },
      { name: 'Taiwan', id: 'tw' },
      { name: 'Ukraine', id: 'ua' },
      { name: 'United States', id: 'us' },
      { name: 'Venezuela', id: 've' },
      { name: 'Zambia', id: 'za' },
    ],
  },
  {
    name: 'Category',
    options: [
      { name: 'Business', id: 'business' },
      { name: 'Entertainment', id: 'entertainment' },
      { name: 'General', id: 'general' },
      { name: 'Health', id: 'health' },
      { name: 'Science', id: 'science' },
      { name: 'Sports', id: 'sports' },
      { name: 'Technology', id: 'technology' },
    ],
  },
  { name: 'Sources', options: sources },
];

export const everythingStrings = [
  {
    name: 'Sort by',
    options: [
      { name: 'Relevancy', id: 'relevancy' },
      { name: 'Popularity', id: 'popularity' },
      { name: 'Published at', id: 'publishedAt' },
    ],
  },
  {
    name: 'Dates',
  },
  { name: 'Sources', options: sources },
  {
    name: 'Language',
    options: [
      { name: 'Arabic', id: 'ar' },
      { name: 'German', id: 'de' },
      { name: 'English', id: 'en' },
      { name: 'Spanish', id: 'es' },
      { name: 'French', id: 'fr' },
      { name: 'Hebrew', id: 'he' },
      { name: 'Italian', id: 'it' },
      { name: 'Dutch', id: 'nl' },
      { name: 'Norwegian', id: 'no' },
      { name: 'Portuguese', id: 'pt' },
      { name: 'Russian', id: 'ru' },
      { name: 'Swedish', id: 'sv' },
      { name: 'Chinese', id: 'zh' },
    ],
  },
];

export const searchInStrings = [
  { name: 'Top Headlines', id: 'top-headlines' },
  { name: 'Everything', id: 'everything' },
];
