import { sources } from '../../mockData/allSources';

export const topHeadlinesStrings = [
  {
    name: 'Country',
    options: [
      'United Arab Emirates',
      'Argentina',
      'Austria',
      'Australia',
      'Belgium',
      'Bulgaria',
      'Brazil',
      'Canada',
      'Chile',
      'China',
      'Colombia',
      'Cuba',
      'Czechia',
      'Germany',
      'Egypt',
      'France',
      'Great Britain ',
      'Greece',
      'Hong Kong',
      'Hungary',
      'Indonesia',
      'Ireland',
      'Israel',
      'India',
      'Italy',
      'Japan',
      'Korea (the Republic of)',
      'Lithuania',
      'Latvia',
      'Morocco',
      'Mexico',
      'Malaysia',
      'Nigeria',
      'Netherlands',
      'Norway',
      'New Zealand',
      'Philippines',
      'Poland',
      'Portugal',
      'Romania',
      'Serbia',
      'Russia',
      'Saudi Arabia',
      'Sweden',
      'Singapore',
      'Slovenia',
      'Slovakia',
      'Thailand',
      'Turkey',
      'Taiwan',
      'Ukraine',
      'United States',
      'Venezuela',
      'Zambia',
    ],
  },
  {
    name: 'Category',
    options: [
      'Business',
      'Entertainment',
      'General',
      'Health',
      'Science',
      'Sports',
      'Technology',
    ],
  },
  { name: 'Sources', options: sources },
];
